"""Verification scaffold and deterministic closure semantics."""

from __future__ import annotations

import hashlib
import math
import os
import shutil
import subprocess
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path
from typing import Protocol

from maida.heal.artifacts import MIN_DISTRIBUTIONAL_SAMPLE, rebuild_window, safe_name
from maida.heal.core import MaidaCLI, validate_report
from maida.heal.events import EventJournal
from maida.heal.killswitch import lock_blocks
from maida.heal.models import (
    Actor,
    ClosureCondition,
    ClosureReport,
    EventConfig,
    EventEnvelope,
    EventType,
    Finding,
    FindingStatus,
    GateConfig,
    GateManifest,
    HealConfig,
    ImportRecord,
    LoopMode,
    WebhookSinkConfig,
    jsonable,
)
from maida.heal.state import (
    StateError,
    StateStore,
    load_gate_manifest,
    read_json,
    save_gate_manifest,
    write_json,
)


class GateError(RuntimeError):
    """A gate scaffold or closure run could not be completed safely."""


class VerificationNotEnabled(GateError):
    """The finding's stream intentionally stops before deterministic closure."""


@dataclass(frozen=True)
class ScaffoldResult:
    repository: Path
    files: tuple[Path, ...]
    holdout_runs: int
    training_runs: int


def _validate_command(command: Sequence[str], *, label: str) -> list[str]:
    if not command:
        raise ValueError(f"{label} command must not be empty")
    if not any("{report}" in item for item in command):
        raise ValueError(f"{label} command must include a {{report}} placeholder")
    return list(command)


def _deterministic_holdout(run_ids: list[str], fraction: float) -> set[str]:
    count = max(1, math.ceil(len(run_ids) * fraction))
    ordered = sorted(
        run_ids,
        key=lambda value: hashlib.sha256(value.encode("utf-8")).hexdigest(),
    )
    return set(ordered[:count])


def _extract_training_baseline(
    state: StateStore,
    core: MaidaCLI,
    *,
    stream_id: str,
    target_name: str,
    training: list[ImportRecord],
) -> Path:
    window = rebuild_window(
        state.windows_dir / "gate-training" / stream_id / safe_name(target_name),
        training,
        state.runs_dir,
    )
    parent = Path(tempfile.mkdtemp(prefix=".gate-extract-", dir=state.root))
    draft = parent / "draft"
    try:
        manifest = core.extract(window=window, out_dir=draft, workflow=target_name)
        workflows = manifest.get("workflows")
        if not isinstance(workflows, list) or len(workflows) != 1:
            raise GateError("Maida did not extract one gate-training workflow")
        selected = workflows[0]
        artifact_dir = (
            selected.get("artifact_dir") if isinstance(selected, dict) else None
        )
        if not isinstance(artifact_dir, str):
            raise GateError("Maida extraction returned no gate-training artifact")
        source = draft / artifact_dir / "baseline.json"
        destination = state.root / "gate-staging" / stream_id / safe_name(target_name)
        destination.mkdir(parents=True, exist_ok=True)
        baseline = destination / "baseline.json"
        shutil.copy2(source, baseline)
        return baseline
    finally:
        shutil.rmtree(parent)


def _workflow_text(events: EventConfig, *, auto_merge: bool) -> str:
    webhook_secrets = sorted(
        {
            sink.secret_env
            for sink in events.sinks
            if isinstance(sink, WebhookSinkConfig)
        }
    )
    environment = ["      GH_TOKEN: ${{ github.token }}"]
    environment.extend(
        f"      {name}: ${{{{ secrets.{name} }}}}" for name in webhook_secrets
    )
    job_environment = "    env:\n" + "\n".join(environment) + "\n"
    contents_permission = "write" if auto_merge else "read"
    template = """# Generated by maida-heal. Review before committing.
name: maida-heal closure

on:
  pull_request:

permissions:
  contents: __CONTENTS_PERMISSION__
  pull-requests: write

jobs:
  verify:
    if: >-
      startsWith(github.head_ref, 'maida-heal/') &&
      !startsWith(github.head_ref, 'maida-heal/revert-')
    runs-on: ubuntu-latest
__JOB_ENVIRONMENT__    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Check kill switch
        run: |
          python - <<'PY'
          import json
          from pathlib import Path
          for path in (Path('.maida-heal/heal.lock'), Path('.maida/heal.lock')):
              if path.is_file():
                  payload = json.loads(path.read_text())
                  if payload.get('scope', 'all') == 'all':
                      raise SystemExit(f'Maida-heal is paused by {path}')
          PY
          test "${MAIDA_HEAL_PAUSED:-false}" != "true"
        env:
          MAIDA_HEAL_PAUSED: ${{ vars.MAIDA_HEAL_PAUSED }}
      - name: Install pinned verifier and loop
        run: uv tool install maida-heal
      - name: Verify finding closure
        shell: bash
        run: |
          finding="${GITHUB_HEAD_REF#maida-heal/}"
          finding="${finding%-a*}"
          maida-heal verify "$finding" --if-enabled
"""
    return template.replace("__JOB_ENVIRONMENT__", job_environment).replace(
        "__CONTENTS_PERMISSION__", contents_permission
    )


def enable_gate(
    state: StateStore,
    config: HealConfig,
    core: MaidaCLI,
    *,
    command: Sequence[str],
    holdout_command: Sequence[str],
    now: datetime,
    holdout_fraction: float = 0.25,
) -> ScaffoldResult:
    if config.fixes is None:
        raise StateError("verify mode requires fixes configuration")
    if state.lock_path.exists():
        raise StateError("Maida-heal is paused; gate scaffolding is disabled")
    gate_command = _validate_command(command, label="gate")
    holdout = _validate_command(holdout_command, label="holdout")
    repo = config.fixes.local_repo()
    if not (repo / ".git").exists():
        raise GateError(f"connected config repository is unavailable: {repo}")
    manifest_mode = (
        config.mode if config.mode.allows(LoopMode.VERIFY) else LoopMode.VERIFY
    )
    stream_modes = {
        stream.id: (
            stream.mode.value if stream.mode is not None else manifest_mode.value
        )
        for stream in config.streams
        if stream.enabled
    }
    existing_manifest = repo / ".maida" / "heal.yaml"
    if existing_manifest.is_file():
        manifest = load_gate_manifest(repo)
        manifest = GateManifest.model_validate(
            {
                **manifest.model_dump(mode="json"),
                "mode": manifest_mode.value,
                "stream_modes": stream_modes,
                "command": gate_command,
                "holdout_command": holdout,
                "holdout_fraction": holdout_fraction,
                "max_attempts_per_finding": config.fixes.max_attempts_per_finding,
                "cooldown_hours": config.fixes.cooldown_hours,
                "events": config.events.model_dump(mode="json"),
                "activation": (
                    config.activation.model_dump(mode="json")
                    if config.activation is not None
                    else None
                ),
                "auto_merge": (
                    config.auto_merge.model_dump(mode="json")
                    if config.auto_merge is not None
                    else None
                ),
            }
        )
        save_gate_manifest(repo, manifest)
        workflow = repo / ".github" / "workflows" / "maida-heal.yml"
        if workflow.exists() and not workflow.read_text(encoding="utf-8").startswith(
            "# Generated by maida-heal"
        ):
            raise GateError(f"refusing to overwrite unmanaged workflow: {workflow}")
        workflow.parent.mkdir(parents=True, exist_ok=True)
        workflow.write_text(
            _workflow_text(config.events, auto_merge=config.auto_merge is not None),
            encoding="utf-8",
        )
        return ScaffoldResult(repo, (existing_manifest, workflow), 0, 0)
    imports = state.load_imports()
    records_by_id = {item.trace_id: item for item in imports.records}
    written: list[Path] = []
    training_total = 0
    holdout_total = 0
    first_policy: Path | None = None
    for metadata_path in sorted(state.streams_dir.glob("*/*/metadata.json")):
        metadata = read_json(metadata_path)
        stream_id = metadata.get("stream_id")
        run_name = metadata.get("run_name")
        baseline_ids = metadata.get("baseline_run_ids")
        if (
            not isinstance(stream_id, str)
            or not isinstance(run_name, str)
            or not isinstance(baseline_ids, list)
            or not all(isinstance(item, str) for item in baseline_ids)
        ):
            raise GateError(f"invalid generated target metadata: {metadata_path}")
        holdout_ids = _deterministic_holdout(baseline_ids, holdout_fraction)
        training = [
            records_by_id[item]
            for item in baseline_ids
            if item not in holdout_ids and item in records_by_id
        ]
        if len(training) < MIN_DISTRIBUTIONAL_SAMPLE:
            raise GateError(
                f"{run_name} needs at least {MIN_DISTRIBUTIONAL_SAMPLE} training "
                f"runs after the {holdout_fraction:g} holdout split; found "
                f"{len(training)}"
            )
        target_name = metadata_path.parent.name
        baseline_source = _extract_training_baseline(
            state,
            core,
            stream_id=stream_id,
            target_name=run_name,
            training=training,
        )
        destination = repo / ".maida" / "heal" / "streams" / stream_id / target_name
        destination.mkdir(parents=True, exist_ok=True)
        baseline_path = destination / "baseline.json"
        policy_path = destination / "policy.yaml"
        shutil.copy2(baseline_source, baseline_path)
        policy_text = (metadata_path.parent / "policy.yaml").read_text(encoding="utf-8")
        policy_path.write_text(
            "# Promoted by maida-heal after deterministic holdout removal.\n"
            f"# gate_training_runs: {len(training)}\n"
            f"# holdout_runs: {len(holdout_ids)}\n" + policy_text,
            encoding="utf-8",
        )
        target_manifest = destination / "target.json"
        write_json(
            target_manifest,
            {
                "schema_version": "1.0.0",
                "stream_id": stream_id,
                "run_name": run_name,
                "training_run_ids": [item.trace_id for item in training],
            },
        )
        holdout_path = repo / ".maida" / "holdout" / stream_id / target_name
        holdout_path.mkdir(parents=True, exist_ok=True)
        holdout_manifest = holdout_path / "manifest.json"
        write_json(
            holdout_manifest,
            {
                "schema_version": "1.0.0",
                "stream_id": stream_id,
                "run_name": run_name,
                "run_ids": sorted(holdout_ids),
                "payloads_included": False,
            },
        )
        written.extend([baseline_path, policy_path, target_manifest, holdout_manifest])
        training_total += len(training)
        holdout_total += len(holdout_ids)
        first_policy = first_policy or policy_path

    if first_policy is None:
        raise GateError("no reviewed generated policy is available to promote")
    root_policy = repo / ".maida" / "policy.yaml"
    if not root_policy.exists():
        shutil.copy2(first_policy, root_policy)
        written.append(root_policy)

    manifest = GateManifest(
        mode=manifest_mode,
        stream_modes=stream_modes,
        command=gate_command,
        holdout_command=holdout,
        holdout_fraction=holdout_fraction,
        max_attempts_per_finding=config.fixes.max_attempts_per_finding,
        cooldown_hours=config.fixes.cooldown_hours,
        events=config.events,
        activation=config.activation,
        auto_merge=config.auto_merge,
    )
    manifest_path = save_gate_manifest(repo, manifest)
    workflow = repo / ".github" / "workflows" / "maida-heal.yml"
    workflow.parent.mkdir(parents=True, exist_ok=True)
    if workflow.exists() and not workflow.read_text(encoding="utf-8").startswith(
        "# Generated by maida-heal"
    ):
        raise GateError(f"refusing to overwrite unmanaged workflow: {workflow}")
    workflow.write_text(
        _workflow_text(config.events, auto_merge=config.auto_merge is not None),
        encoding="utf-8",
    )
    written.extend([manifest_path, workflow])

    promoted = repo / ".maida" / "findings"
    promoted.mkdir(parents=True, exist_ok=True)
    for finding_path in sorted(state.local_findings_dir.glob("mh-*.json")):
        destination = promoted / finding_path.name
        shutil.copy2(finding_path, destination)
        finding_path.unlink()
        written.append(destination)

    if config.gate is None:
        config.gate = GateConfig(
            enabled_at=now,
            command=gate_command,
            holdout_command=holdout,
            holdout_fraction=holdout_fraction,
        )
        config.mode = LoopMode.VERIFY
    state.save_config(config)
    return ScaffoldResult(
        repository=repo,
        files=tuple(written),
        holdout_runs=holdout_total,
        training_runs=training_total,
    )


class ClosureRunner(Protocol):
    def run(self, command: Sequence[str], *, cwd: Path) -> int: ...


class SubprocessClosureRunner:
    def run(self, command: Sequence[str], *, cwd: Path) -> int:
        completed = subprocess.run(
            list(command), cwd=cwd, text=True, capture_output=True, check=False
        )
        return completed.returncode


class Commenter(Protocol):
    def comment(self, pull_request: int, body: str, *, repo: Path) -> None: ...


class GitHubCommenter:
    def comment(self, pull_request: int, body: str, *, repo: Path) -> None:
        descriptor, name = tempfile.mkstemp(prefix="maida-heal-closure-", suffix=".md")
        path = Path(name)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                handle.write(body)
            completed = subprocess.run(
                ["gh", "pr", "comment", str(pull_request), "--body-file", str(path)],
                cwd=repo,
                text=True,
                capture_output=True,
                check=False,
            )
        finally:
            path.unlink(missing_ok=True)
        if completed.returncode != 0:
            raise GateError("could not comment the closure report on the pull request")


def _target_paths(repo: Path, finding: Finding) -> tuple[Path, Path, Path]:
    root = repo / ".maida" / "heal" / "streams" / finding.stream_id
    candidates: list[tuple[Path, dict[str, object]]] = []
    for manifest_path in sorted(root.glob("*/target.json")):
        candidates.append((manifest_path.parent, read_json(manifest_path)))
    requested = next(
        (failure.target for failure in finding.metric_failures if failure.target), None
    )
    selected = next(
        (
            path
            for path, payload in candidates
            if requested is not None and payload.get("run_name") == requested
        ),
        candidates[0][0] if len(candidates) == 1 else None,
    )
    if selected is None:
        raise GateError("finding does not identify one promoted gate target")
    holdout = repo / ".maida" / "holdout" / finding.stream_id / selected.name
    return (
        selected / "baseline.json",
        selected / "policy.yaml",
        holdout / "manifest.json",
    )


def _render_command(
    command: Sequence[str],
    *,
    finding: Finding,
    report: Path,
    baseline: Path,
    policy: Path,
    holdout: Path,
    suite: str,
) -> list[str]:
    values = {
        "finding": finding.id,
        "report": str(report),
        "baseline": str(baseline),
        "policy": str(policy),
        "holdout": str(holdout),
        "suite": suite,
    }
    try:
        return [item.format_map(values) for item in command]
    except KeyError as error:
        raise GateError(f"unknown gate command placeholder: {error.args[0]}") from error


def _load_report(path: Path) -> dict[str, object]:
    if not path.is_file():
        raise GateError(f"gate command did not write its report: {path}")
    return validate_report(read_json(path))


def _metric_passes(report: dict[str, object], metrics: tuple[str, ...]) -> bool:
    aggregates = report.get("aggregate_results")
    if not isinstance(aggregates, list):
        return False
    by_name: dict[str, list[object]] = {}
    for item in aggregates:
        if isinstance(item, dict) and isinstance(item.get("check_name"), str):
            by_name.setdefault(item["check_name"], []).append(item.get("verdict"))
    return all(
        by_name.get(metric) and set(by_name[metric]) == {"pass"} for metric in metrics
    )


def _failed_names(report: dict[str, object]) -> list[str]:
    aggregates = report.get("aggregate_results")
    if not isinstance(aggregates, list):
        return ["invalid-report"]
    return [
        str(item.get("check_name"))
        for item in aggregates
        if isinstance(item, dict) and item.get("verdict") == "fail"
    ]


def closure_markdown(report: ClosureReport) -> str:
    icon = "✅" if report.verdict == "closed" else "❌"
    lines = [f"## {icon} Maida-heal closure: {report.verdict}", ""]
    for condition in report.conditions:
        marker = "PASS" if condition.passed else "FAIL"
        lines.append(f"- **{condition.name} — {marker}:** {condition.detail}")
    lines.extend(
        [
            "",
            "The fix writer did not judge this result. Every verdict above came from "
            "Maida report JSON and deterministic closure rules.",
            "",
            "For production-drift findings, this replays repository scenarios; the "
            "post-merge watch window supplies live confirmation.",
        ]
    )
    return "\n".join(lines) + "\n"


def _queue_closure_event(
    repo: Path,
    manifest: GateManifest,
    finding: Finding,
    report: ClosureReport,
    *,
    stream_mode: LoopMode,
) -> None:
    """Idempotently project one persisted closure into the machine event API."""
    attempt = finding.attempts[-1] if finding.attempts else None
    if report.verdict == "closed":
        release_mode = (
            "auto_merge"
            if stream_mode is LoopMode.FULL and manifest.auto_merge is not None
            else "handoff"
            if stream_mode is LoopMode.FULL
            else "verify_only"
        )
        event = EventEnvelope.create(
            event_type=EventType.FIX_VERIFIED,
            occurred_at=report.generated_at,
            dedupe_key=(f"{finding.id}:closure:{report.generated_at.isoformat()}"),
            stream_id=finding.stream_id,
            finding_id=finding.id,
            data={
                "finding_id": finding.id,
                "pull_request_number": (
                    attempt.pull_request_number if attempt is not None else None
                ),
                "release_mode": release_mode,
                "release_ready": stream_mode is LoopMode.FULL,
                "closure_report": jsonable(report),
            },
        )
    else:
        event = EventEnvelope.create(
            event_type=EventType.FIX_REJECTED,
            occurred_at=report.generated_at,
            dedupe_key=(
                f"{finding.id}:closure-rejected:{report.generated_at.isoformat()}"
            ),
            stream_id=finding.stream_id,
            finding_id=finding.id,
            data={
                "finding_id": finding.id,
                "attempt": attempt.number if attempt is not None else None,
                "reason": "One or more deterministic closure conditions failed.",
                "changed_paths": (attempt.changed_paths if attempt is not None else []),
            },
        )
    journal = EventJournal(repo, manifest.events)
    journal.queue(event)
    journal.flush()


def _recover_persisted_closure(
    repo: Path,
    manifest: GateManifest,
    finding: Finding,
    *,
    finding_path: Path,
    stream_mode: LoopMode,
    now: datetime,
) -> ClosureReport:
    expected = Path(".maida") / "findings" / "closure" / f"{finding.id}.json"
    if finding.closure_report != expected.as_posix():
        raise GateError(
            f"finding {finding.id} has terminal state without its closure report"
        )
    report = ClosureReport.model_validate(read_json(repo / expected))
    expected_status = (
        FindingStatus.CLOSED
        if report.verdict == "closed"
        else FindingStatus.FIX_REJECTED
    )
    if report.finding_id != finding.id or finding.status is not expected_status:
        raise GateError(f"finding {finding.id} has inconsistent closure state")
    _queue_closure_event(
        repo,
        manifest,
        finding,
        report,
        stream_mode=stream_mode,
    )
    if (
        report.verdict == "closed"
        and stream_mode is LoopMode.FULL
        and manifest.auto_merge is not None
        and finding.merge is None
    ):
        from maida.heal.release import maybe_auto_merge

        decision = maybe_auto_merge(repo, finding, manifest.auto_merge, now=now)
        if decision.merged:
            write_json(finding_path, jsonable(finding))
    return report


def verify_closure(
    repo: Path,
    finding_id: str,
    *,
    now: datetime,
    runner: ClosureRunner | None = None,
    commenter: Commenter | None = None,
) -> ClosureReport:
    repo = repo.resolve()
    manifest = load_gate_manifest(repo)
    if (
        lock_blocks(repo / ".maida-heal" / "heal.lock", operation="verify")
        or lock_blocks(repo / ".maida" / "heal.lock", operation="verify")
        or os.environ.get("MAIDA_HEAL_PAUSED", "").lower() == "true"
    ):
        raise StateError("Maida-heal is paused; CI verification is disabled")
    finding_path = repo / ".maida" / "findings" / f"{finding_id}.json"
    finding = Finding.model_validate(read_json(finding_path))
    stream_mode = manifest.stream_modes.get(finding.stream_id, manifest.mode)
    if not stream_mode.allows(LoopMode.VERIFY):
        raise VerificationNotEnabled(
            f"stream {finding.stream_id} is configured for {stream_mode.value}; "
            "deterministic closure was intentionally skipped"
        )
    if finding.status in {FindingStatus.CLOSED, FindingStatus.FIX_REJECTED}:
        return _recover_persisted_closure(
            repo,
            manifest,
            finding,
            finding_path=finding_path,
            stream_mode=stream_mode,
            now=now,
        )
    if finding.status is not FindingStatus.FIX_PROPOSED:
        raise GateError(
            f"finding {finding.id} cannot verify from {finding.status.value}"
        )
    baseline, policy, holdout_manifest = _target_paths(repo, finding)
    reports = repo / ".maida" / "heal" / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    candidate_path = reports / f"{finding.id}-candidate.json"
    holdout_path = reports / f"{finding.id}-holdout.json"
    candidate_path.unlink(missing_ok=True)
    holdout_path.unlink(missing_ok=True)
    executor = runner or SubprocessClosureRunner()
    candidate_command = _render_command(
        manifest.command,
        finding=finding,
        report=candidate_path,
        baseline=baseline,
        policy=policy,
        holdout=holdout_manifest,
        suite="candidate",
    )
    candidate_exit = executor.run(candidate_command, cwd=repo)
    if candidate_exit not in {0, 1}:
        raise GateError(f"candidate gate exited {candidate_exit}")
    candidate = _load_report(candidate_path)
    holdout_command = manifest.holdout_command or manifest.command
    rendered_holdout = _render_command(
        holdout_command,
        finding=finding,
        report=holdout_path,
        baseline=baseline,
        policy=policy,
        holdout=holdout_manifest,
        suite="holdout",
    )
    holdout_exit = executor.run(rendered_holdout, cwd=repo)
    if holdout_exit not in {0, 1}:
        raise GateError(f"holdout gate exited {holdout_exit}")
    holdout_report = _load_report(holdout_path)

    candidate_pointer = candidate_path.relative_to(repo).as_posix()
    holdout_pointer = holdout_path.relative_to(repo).as_posix()
    specific = _metric_passes(candidate, finding.metric_names)
    holdouts_pass = holdout_report.get("verdict") == "pass" and not _failed_names(
        holdout_report
    )
    failed = _failed_names(candidate)
    no_new = candidate.get("verdict") == "pass" and not failed
    failed_label = ", ".join(failed) or "none (inconclusive)"
    conditions = [
        ClosureCondition(
            name="specific_metrics",
            passed=specific,
            evidence_pointers=[candidate_pointer],
            detail=(
                "Every metric named by the finding is PASS."
                if specific
                else "The candidate report is green for an unrelated reason or the "
                "finding metric is missing/not PASS."
            ),
        ),
        ClosureCondition(
            name="holdouts",
            passed=holdouts_pass,
            evidence_pointers=[holdout_pointer],
            detail=(
                "All withheld scenarios PASS."
                if holdouts_pass
                else "At least one withheld scenario did not PASS."
            ),
        ),
        ClosureCondition(
            name="no_new_failures",
            passed=no_new,
            evidence_pointers=[candidate_pointer, holdout_pointer],
            detail=(
                "The full candidate gate is PASS with no failed metric."
                if no_new
                else f"The full candidate gate is not PASS; failures: {failed_label}."
            ),
        ),
    ]
    closed = all(item.passed for item in conditions)
    report = ClosureReport(
        finding_id=finding.id,
        generated_at=now,
        maida_report_version=str(candidate["report_version"]),
        verdict="closed" if closed else "rejected",
        conditions=conditions,
    )
    closure_dir = repo / ".maida" / "findings" / "closure"
    closure_dir.mkdir(parents=True, exist_ok=True)
    closure_path = closure_dir / f"{finding.id}.json"
    write_json(closure_path, jsonable(report))
    finding.transition(
        FindingStatus.VERIFYING,
        actor=Actor.VERIFIER,
        action="verification_started",
        detail="Candidate and holdout Maida gates completed.",
        at=now,
    )
    finding.transition(
        FindingStatus.CLOSED if closed else FindingStatus.FIX_REJECTED,
        actor=Actor.VERIFIER,
        action="finding_closed" if closed else "fix_rejected",
        detail="All closure conditions passed."
        if closed
        else "One or more deterministic closure conditions failed.",
        at=now,
    )
    finding.closure_report = closure_path.relative_to(repo).as_posix()
    if not closed:
        finding.cooldown_until = now + timedelta(hours=manifest.cooldown_hours)
    if finding.attempts:
        finding.attempts[-1].outcome = "verified" if closed else "failed"
        finding.attempts[-1].finished_at = now
    write_json(finding_path, jsonable(finding))
    _queue_closure_event(
        repo,
        manifest,
        finding,
        report,
        stream_mode=stream_mode,
    )
    if commenter is not None and finding.attempts:
        pr = finding.attempts[-1].pull_request_number
        if pr is not None:
            commenter.comment(pr, closure_markdown(report), repo=repo)
    if closed and stream_mode is LoopMode.FULL and manifest.auto_merge is not None:
        from maida.heal.release import maybe_auto_merge

        decision = maybe_auto_merge(repo, finding, manifest.auto_merge, now=now)
        if decision.merged:
            write_json(finding_path, jsonable(finding))
    return report
