from datetime import datetime, timezone
from pathlib import Path

from maida_heal.disablement import disable_feature
from maida_heal.models import (
    Actor,
    AutoMergeConfig,
    Finding,
    FindingSource,
    FixesConfig,
    GateConfig,
    GateManifest,
    HealConfig,
    HistoryEvent,
    LangfuseConfig,
    MetricFailure,
)
from maida_heal.state import StateStore, load_gate_manifest, save_gate_manifest

NOW = datetime(2026, 8, 11, 12, tzinfo=timezone.utc)


def setup_enabled(tmp_path: Path) -> tuple[StateStore, HealConfig, Path, Finding]:
    repo = tmp_path / "repo"
    (repo / ".maida" / "heal" / "streams").mkdir(parents=True)
    (repo / ".maida" / "holdout").mkdir()
    (repo / ".maida" / "policy.yaml").write_text("version: 2\n", encoding="utf-8")
    workflow = repo / ".github" / "workflows" / "maida-heal.yml"
    workflow.parent.mkdir(parents=True)
    workflow.write_text("# Generated by maida-heal. Review before committing.\n")
    state = StateStore(tmp_path / "control")
    config = HealConfig(
        langfuse=LangfuseConfig(
            host="https://example.test", credential_source="environment"
        ),
        fixes=FixesConfig(
            repo="maida-ai/example",
            repo_local_path=str(repo),
            fixer="command",
            command=["fixture-fixer"],
        ),
        gate=GateConfig(
            command=["gate", "{report}"],
            holdout_command=["holdout", "{report}"],
        ),
        auto_merge=AutoMergeConfig(),
    )
    state.save_config(config)
    save_gate_manifest(
        repo,
        GateManifest(
            command=["gate", "{report}"],
            holdout_command=["holdout", "{report}"],
            holdout_fraction=0.25,
            auto_merge=config.auto_merge,
        ),
    )
    finding = Finding(
        id="mh-20260811-0123456789",
        stream="support-agent",
        stream_id="support-agent-aabbccdd",
        source=FindingSource.SHADOW_WATCH,
        title="step_count drift",
        summary="Structural drift.",
        metric_failures=[
            MetricFailure(
                metric="step_count",
                kind="distributional",
                decision_rule="wilson_one_sided",
                run_ids=["a" * 32],
                evidence_pointer="report.json",
            )
        ],
        history=[
            HistoryEvent(
                timestamp=NOW,
                actor=Actor.SYSTEM,
                action="finding_opened",
                detail="Fixture finding.",
            )
        ],
    )
    state.save_finding(finding, config)
    return state, config, repo, finding


def test_disable_auto_merge_only_updates_local_and_gate_configuration(
    tmp_path: Path,
) -> None:
    state, config, repo, _finding = setup_enabled(tmp_path)

    result = disable_feature(state, config, "auto-merge")

    assert result.config.tier == 3
    assert load_gate_manifest(repo).auto_merge is None
    assert (repo / ".maida" / "heal").is_dir()


def test_disable_gate_demotes_findings_and_removes_only_managed_scaffold(
    tmp_path: Path,
) -> None:
    state, config, repo, finding = setup_enabled(tmp_path)

    result = disable_feature(state, config, "gate")

    assert result.config.tier == 2
    assert state.load_finding(finding.id, result.config).id == finding.id
    assert not (repo / ".maida" / "heal").exists()
    assert not (repo / ".maida" / "holdout").exists()
    assert not (repo / ".maida" / "heal.yaml").exists()
    assert not (repo / ".github" / "workflows" / "maida-heal.yml").exists()
    assert (repo / ".maida" / "policy.yaml").is_file()
    assert ".maida/policy.yaml" in result.preserved


def test_disable_fixes_cascades_later_tiers_but_keeps_findings(tmp_path: Path) -> None:
    state, config, repo, finding = setup_enabled(tmp_path)

    result = disable_feature(state, config, "fixes")

    assert result.config.tier == 1
    assert result.config.fixes is None
    assert state.load_finding(finding.id, result.config).id == finding.id
    assert (repo / ".maida" / "policy.yaml").is_file()
