"""Build immutable baseline samples and conservative generated policies."""

from __future__ import annotations

import json
import os
import shutil
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from maida_heal.core import MaidaCLI
from maida_heal.models import ImportRecord, StreamConfig
from maida_heal.state import StateStore, write_json

# Maida 0.5.0's public loader currently reports n_min=10 for coverage 0.90.
# Keep the orchestration aligned with the released verifier's accepted contract.
MIN_DISTRIBUTIONAL_SAMPLE = 10


@dataclass(frozen=True)
class TargetArtifacts:
    stream_id: str
    run_name: str
    baseline: Path
    policy: Path
    recent_window: Path
    baseline_count: int
    recent_count: int


def safe_name(value: str) -> str:
    import hashlib
    import re

    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")[:48]
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:10]
    return f"{slug or 'target'}-{digest}"


def split_baseline_recent(
    records: Iterable[ImportRecord], *, recent_fraction: float = 0.25
) -> tuple[list[ImportRecord], list[ImportRecord]]:
    ordered = sorted(records, key=lambda item: (item.started_at, item.trace_id))
    if len(ordered) < 2:
        return ordered, []
    recent_count = max(1, int(len(ordered) * recent_fraction + 0.999999))
    return ordered[:-recent_count], ordered[-recent_count:]


def rebuild_window(path: Path, records: Iterable[ImportRecord], runs_dir: Path) -> Path:
    """Build a read-only hard-link view without copying or mutating source traces.

    Maida deliberately rejects storage-directory symlinks that escape the selected
    native window. Both paths live beneath `.maida-heal/`, so hard links preserve the
    exact validated bytes without duplicating payload data.
    """
    resolved_parent = path.parent.resolve()
    path = path.resolve()
    if not path.is_relative_to(resolved_parent):
        raise ValueError("window path escaped its state parent")
    if path.exists():
        shutil.rmtree(path)
    native = path / "runs"
    native.mkdir(parents=True)
    for record in records:
        source = (runs_dir / record.trace_id).resolve()
        if not source.is_dir() or not source.is_relative_to(runs_dir.resolve()):
            raise ValueError(f"imported run is missing: {record.trace_id}")
        destination = native / record.trace_id
        destination.mkdir()
        for source_file in source.iterdir():
            if not source_file.is_file() or source_file.is_symlink():
                raise ValueError(
                    f"imported run has an unsupported entry: {source_file.name}"
                )
            os.link(source_file, destination / source_file.name)
    return native


def _generated_policy(
    *,
    generated_at: datetime,
    window_start: datetime,
    window_end: datetime,
    run_count: int,
    draft_summary: dict[str, Any],
    all_successful: bool,
) -> str:
    if run_count < MIN_DISTRIBUTIONAL_SAMPLE:
        raise ValueError("insufficient baseline sample for a generated policy")
    coverage = 0.95 if run_count >= 19 else 0.90
    header = [
        "# Generated by maida-heal; review before enabling as a merge gate.",
        f"# generated_at: {generated_at.isoformat()}",
        f"# sample_window: {window_start.isoformat()} to {window_end.isoformat()}",
        f"# sample_runs: {run_count}",
        "# Every active metric below has generated: true provenance in this header.",
        "version: 2",
        "fail_fast: false",
        "metrics:",
    ]
    metrics: dict[str, dict[str, object]] = {}
    for name in ("step_count", "tool_call_count", "latency_ms", "cost_tokens"):
        metrics[name] = {
            "kind": "distributional",
            "direction": "upper",
            "coverage": coverage,
            "confidence": 0.95,
            "mode": "gating",
        }
    if all_successful:
        metrics["task_pass_rate"] = {
            "kind": "statistical",
            "direction": "lower",
            "threshold": 0.90,
            "confidence": 0.95,
            "mode": "report_only",
            "success_predicate": "all_invariants_passed",
        }
    lines = list(header)
    for name, definition in metrics.items():
        lines.append(f"  # generated: true; baseline evidence: {run_count} runs")
        rendered = yaml.safe_dump(
            {name: definition}, sort_keys=False, default_flow_style=False
        ).rstrip()
        lines.extend(f"  {line}" for line in rendered.splitlines())

    tools = draft_summary.get("tools")
    common_tools = tools.get("intersection") if isinstance(tools, dict) else None
    lines.extend(
        [
            "",
            "# Suggested invariants (not enforced):",
            f"# Evidence: {run_count}/{run_count} baseline runs ended successfully.",
            "# stop_condition_reached: {kind: invariant, require: true}",
            f"# Evidence: {run_count}/{run_count} baseline runs reported no loop.",
            "# no_loops: {kind: invariant, require: true}",
        ]
    )
    if isinstance(common_tools, list) and common_tools:
        encoded = json.dumps(common_tools, ensure_ascii=False)
        lines.extend(
            [
                f"# Evidence: tools appeared in {run_count}/{run_count} baseline runs.",
                f"# required_tools: {{kind: invariant, all_of: {encoded}}}",
            ]
        )
    return "\n".join(lines) + "\n"


def prepare_stream_artifacts(
    state: StateStore,
    core: MaidaCLI,
    stream: StreamConfig,
    records: list[ImportRecord],
    *,
    generated_at: datetime,
) -> list[TargetArtifacts]:
    """Create one core-verifiable target for each run name inside a stream."""
    targets: list[TargetArtifacts] = []
    by_name: dict[str, list[ImportRecord]] = {}
    for item in records:
        by_name.setdefault(item.run_name, []).append(item)
    for run_name, target_records in sorted(by_name.items()):
        baseline_records, recent_records = split_baseline_recent(target_records)
        if len(baseline_records) < MIN_DISTRIBUTIONAL_SAMPLE or not recent_records:
            continue
        artifact_root = state.streams_dir / stream.id / safe_name(run_name)
        artifact_root.mkdir(parents=True, exist_ok=True)
        baseline_window = rebuild_window(
            state.windows_dir / stream.id / safe_name(run_name) / "baseline",
            baseline_records,
            state.runs_dir,
        )
        recent_window = rebuild_window(
            state.windows_dir / stream.id / safe_name(run_name) / "recent",
            recent_records,
            state.runs_dir,
        )
        temporary_parent = Path(tempfile.mkdtemp(prefix=".extract-", dir=state.root))
        draft_dir = temporary_parent / "draft"
        try:
            manifest = core.extract(
                window=baseline_window,
                out_dir=draft_dir,
                workflow=run_name,
            )
            workflows = manifest.get("workflows")
            if not isinstance(workflows, list) or len(workflows) != 1:
                raise ValueError("Maida extraction did not return exactly one workflow")
            summary = workflows[0]
            if not isinstance(summary, dict) or not isinstance(
                summary.get("artifact_dir"), str
            ):
                raise ValueError("Maida extraction returned an invalid workflow")
            source = draft_dir / summary["artifact_dir"] / "baseline.json"
            baseline_path = artifact_root / "baseline.json"
            shutil.copy2(source, baseline_path)
            policy_path = artifact_root / "policy.yaml"
            policy_path.write_text(
                _generated_policy(
                    generated_at=generated_at,
                    window_start=baseline_records[0].started_at,
                    window_end=baseline_records[-1].ended_at,
                    run_count=len(baseline_records),
                    draft_summary=summary,
                    all_successful=all(
                        item.status == "ok" for item in baseline_records
                    ),
                ),
                encoding="utf-8",
            )
            write_json(
                artifact_root / "metadata.json",
                {
                    "schema_version": "1.0.0",
                    "stream_id": stream.id,
                    "run_name": run_name,
                    "baseline_run_ids": [item.trace_id for item in baseline_records],
                    "recent_run_ids": [item.trace_id for item in recent_records],
                },
            )
        finally:
            shutil.rmtree(temporary_parent)
        targets.append(
            TargetArtifacts(
                stream_id=stream.id,
                run_name=run_name,
                baseline=baseline_path,
                policy=policy_path,
                recent_window=recent_window,
                baseline_count=len(baseline_records),
                recent_count=len(recent_records),
            )
        )
    return targets
