"""Reversible tier walkback that removes only Maida-heal-managed scaffolding."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from maida_heal.models import HealConfig
from maida_heal.state import StateStore, load_gate_manifest, save_gate_manifest


@dataclass(frozen=True)
class DisableResult:
    config: HealConfig
    removed: tuple[str, ...]
    preserved: tuple[str, ...]


def _remove_tree(repo: Path, path: Path, removed: list[str]) -> None:
    resolved = path.resolve()
    if not resolved.is_relative_to(repo.resolve()) or resolved == repo.resolve():
        raise ValueError(f"refusing to remove an unsafe managed path: {path}")
    if path.exists():
        shutil.rmtree(path)
        removed.append(path.relative_to(repo).as_posix())


def _disable_auto_merge(
    state: StateStore,
    config: HealConfig,
    removed: list[str],
) -> None:
    if config.auto_merge is None:
        return
    if config.fixes is not None and config.gate is not None:
        repo = Path(config.fixes.repo_local_path).resolve()
        manifest = load_gate_manifest(repo)
        manifest.auto_merge = None
        save_gate_manifest(repo, manifest)
    config.auto_merge = None
    removed.append("auto_merge configuration")
    state.save_config(config)


def _demote_findings(state: StateStore, repo: Path) -> None:
    source = repo / ".maida" / "findings"
    if not source.exists():
        return
    state.local_findings_dir.mkdir(parents=True, exist_ok=True)
    for path in sorted(source.glob("mh-*.json")):
        shutil.copy2(path, state.local_findings_dir / path.name)
    closure = source / "closure"
    if closure.exists():
        destination = state.local_findings_dir / "closure"
        destination.mkdir(parents=True, exist_ok=True)
        for path in sorted(closure.glob("mh-*.json")):
            shutil.copy2(path, destination / path.name)


def _disable_gate(
    state: StateStore,
    config: HealConfig,
    removed: list[str],
    preserved: list[str],
) -> None:
    if config.gate is None or config.fixes is None:
        return
    _disable_auto_merge(state, config, removed)
    repo = Path(config.fixes.repo_local_path).resolve()
    _demote_findings(state, repo)
    workflow = repo / ".github" / "workflows" / "maida-heal.yml"
    if workflow.exists():
        if workflow.read_text(encoding="utf-8").startswith("# Generated by maida-heal"):
            workflow.unlink()
            removed.append(workflow.relative_to(repo).as_posix())
        else:
            preserved.append(workflow.relative_to(repo).as_posix())
    manifest = repo / ".maida" / "heal.yaml"
    if manifest.exists():
        manifest.unlink()
        removed.append(manifest.relative_to(repo).as_posix())
    mirrored_lock = repo / ".maida" / "heal.lock"
    if mirrored_lock.exists():
        mirrored_lock.unlink()
        removed.append(mirrored_lock.relative_to(repo).as_posix())
    _remove_tree(repo, repo / ".maida" / "heal", removed)
    _remove_tree(repo, repo / ".maida" / "holdout", removed)
    _remove_tree(repo, repo / ".maida" / "findings", removed)
    policy = repo / ".maida" / "policy.yaml"
    if policy.exists():
        preserved.append(policy.relative_to(repo).as_posix())
    config.gate = None
    state.save_config(config)


def disable_feature(
    state: StateStore,
    config: HealConfig,
    feature: str,
) -> DisableResult:
    """Disable one tier and everything above it without deleting user code."""
    normalized = feature.strip().lower().replace("_", "-")
    if normalized not in {"fixes", "gate", "auto-merge"}:
        raise ValueError("feature must be fixes, gate, or auto-merge")
    removed: list[str] = []
    preserved: list[str] = []
    if normalized == "auto-merge":
        if config.auto_merge is None:
            raise ValueError("auto-merge is not enabled")
        _disable_auto_merge(state, config, removed)
    elif normalized == "gate":
        if config.gate is None:
            raise ValueError("the gate is not enabled")
        _disable_gate(state, config, removed, preserved)
    else:
        if config.fixes is None:
            raise ValueError("fixes are not enabled")
        _disable_gate(state, config, removed, preserved)
        config.fixes = None
        removed.append("fixes configuration")
        state.save_config(config)
    return DisableResult(config, tuple(removed), tuple(preserved))
